server:
  port: 8502
  servlet:
    context-path: /api
  connection-timeout: 1800000
  tomcat:
    max-http-post-size: -1
spring:
  application:
    name: spring-data-en-decoder
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss



mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Dao.xml
 #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.data.en.decoder
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
       #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


#logging
logging:
  config: classpath:logback-dev.xml
